[alembic]
run_cfg = path

script_location = mi-framework-ia

sqlalchemy.url = postgresql+psycopg2://mindflow_user:mindflow_pass@localhost:5432/mindflow_ai

default_schema = public

prepend_sys_path = ./alembic

plugin = revision generation

mathjax = true

pdf_render = true

startup_helpers = []

event_hooks = true

pluggable_django = false